### PR TITLE
Support for Pre-Created JWTs in VST connections

### PR DESCRIPTION
**Pull request by ruidscampos**
Add a new AuthenticationTypeRawJWT that allows using JWTs generated outside of the Authentication flow inside VST connections.

Enables management of credentials by an outside service without sharing the password with an executor, instead using a short lived JWT.
This is easy to do with HTTP using the RawAuthentication, but VST didn't support it. 
As such, adding Raw JWT support to VST.

### CODE REVIEW

**Comment by ruidscampos** [comment]
I've sent the signed CLA under my name, please check the inbox.

**Comment by cw00dw0rd** [comment]
> I've sent the signed CLA under my name, please check the inbox.

Thanks for the PR and sending that in, I will check with the team and get back to you.

**Comment by cw00dw0rd** [comment]
@cla-bot recheck

**Comment by cw00dw0rd** [comment]
@cla-bot check

**Review by nikita-vanyasin — CHANGES_REQUESTED** [review]
Hello @ruidscampos 
Thanks for contribution!
Can you please clarify why `AuthenticationTypeRaw` don't work for you?

On proposed changes:
1) New `AuthenticationTypeRawJWT` is not added to normal "http" protocol implementation (`*httpConnection.SetAuthentication()`). That might be quite unexpected for other users. Please add implementation there too.
2) Please adjust tests to ensure your feature will work correctly:
 2a) `TestIsAuthenticationTheSame`
 2b) You can run all test suite using your new auth type: adjust `client_test.go -> createAuthenticationFromEnv` accordingly.

**Comment by nikita-vanyasin** [comment]
> Can you please clarify why you added new type instead of implementing `AuthenticationTypeRaw` for VST connection?


^ previous comment updated

**Comment by ruidscampos** [comment]
> Hello @ruidscampos Thanks for contribution! Can you please clarify why you added new type instead of implementing `AuthenticationTypeRaw` for VST connection?
> 
> On proposed changes:
> 
>     1. New `AuthenticationTypeRawJWT` is not added to normal "http" protocol implementation (`*httpConnection.SetAuthentication()`). That might be quite unexpected for other users. Please add implementation there too.
> 
>     2. Please adjust tests to ensure your feature will work correctly:
>        2a) `TestIsAuthenticationTheSame`
>        2b) You can run all test suite using your new auth type: adjust `client_test.go -> createAuthenticationFromEnv` accordingly.

Hi @nikita-vanyasin, regarding your initial question and point 1:

AuthenticationTypeRaw assumes you can send Raw Authentication for both JWT and Basic authentication, which is something you can do for HTTP, but not true for VST, as it needs to be framed, not added to a header, making it confusing for users if they decide to use it.

AuthenticationTypeRaw isn't accepted currently in VST, throwing an error, thus the addition of AuthenticationTypeRawJWT for VST, throwing an error in HTTP which is inline with the error thrown in VST.

If one is to break away from this, then it makes more sense to have a AuthenticationTypeRawBasic and AuthenticationTypeRawJWT and deprecate AuthenticationTypeRaw, with the caveat that AuthenticationTypeRawBasic will never be applicable to VST unless it is changes to support both text value and framing.

Let me know what you think is the prefered option, to keep the current pattern and the implementation as is, or to deprecate Raw in favor of a split option, and how to handle Basic Auth in VST.


Regarding point 2, I'll update those as soon as I get a chance.

**Comment by nikita-vanyasin** [comment]
@ruidscampos
I see, thank you!
I think `AuthenticationType*` are meant to be protocol-independent, so it is better to implement `AuthenticationTypeRaw` support for VST.

I don't think it will be confusing - just update comment for `AuthenticationTypeRaw` const.


@ajanikow @jwierzbo WDYT?

**Comment by nikita-vanyasin** [comment]
@ruidscampos a general question: can you please describe why you want to use VST?
Our current priority is adding more features to go-driver v2 which does not have have support for VST. It also has support for customization of Authentication header.

**Comment by ruidscampos** [comment]
> @ruidscampos a general question: can you please describe why you want to use VST? Our current priority is adding more features to go-driver v2 which does not have have support for VST. It also has support for customization of Authentication header.

Performance reasons, we use it on operational realtime platform.

Ideally we'd want the ability to have a persistent reusable connection to the DB with a binary protocol that we could pre-compile on the client towards reducing the time it takes to parse a request, and also reduce the amount of information flowing through the network.

VST filled a bit of that gap.

**Comment by ruidscampos** [comment]
> @ruidscampos I see, thank you! I think `AuthenticationType*` are meant to be protocol-independent, so it is better to implement `AuthenticationTypeRaw` support for VST.
> 
> I don't think it will be confusing - just update comment for `AuthenticationTypeRaw` const.
> 
> @ajanikow @jwierzbo WDYT?

Sure, i'll apply that change as well.

**Comment by ruidscampos** [comment]
Web-sockets are a bit of a hassle, but we've got good results with grpc streaming in some of our services, that could be a good alternative if you decide to move away from VST towards something more standard.

**Comment by nikita-vanyasin** [comment]
> Web-sockets are a bit of a hassle, but we've got good results with grpc streaming in some of our services, that could be a good alternative if you decide to move away from VST towards something more standard.

Thank you!

FYI: go-driver/v2 tries to parse all responses as streams where possible (compared to V1-http).
In v2 it is also possible to make connection more "persistent" as you can use HTTP/2 and have full control of http2.Transport config.

**Comment by ruidscampos** [comment]
> > Web-sockets are a bit of a hassle, but we've got good results with grpc streaming in some of our services, that could be a good alternative if you decide to move away from VST towards something more standard.
> 
> Thank you!
> 
> FYI: go-driver/v2 tries to parse all responses as streams where possible (compared to V1-http). In v2 it is also possible to make connection more "persistent" as you can use HTTP/2 and have full control of http2.Transport config.

That sounds promising, will have to test it out once it's ready.

**Comment by ruidscampos** [comment]
@nikita-vanyasin submitted the refactor with your previous indications:
- reuse AuthenticationTypeRaw and update the comment
- update of client_test.go -> createAuthenticationFromEnv to support vst raw authentication using jwt

Didn't update TestIsAuthenticationTheSame as this is used only in http and the main purpose of the test is for repeatable connections, which is not present in VST.

**Comment by nikita-vanyasin** [comment]
Hello @ruidscampos thank you!
I didn't check yet, but is it possible to abstract away the `encryption` field also? So end-user will provide not only token but also the encryption method? That way `AuthenticationTypeRaw` will be truly _Raw_. Currently it looks a bit inconsistent.

**Comment by ruidscampos** [comment]
> Hello @ruidscampos thank you! I didn't check yet, but is it possible to abstract away the `encryption` field also? So end-user will provide not only token but also the encryption method? That way `AuthenticationTypeRaw` will be truly _Raw_. Currently it looks a bit inconsistent.

Not sure I understand your request.

VST needs to encode the data, meaning it can only do jwt as raw, otherwise you need to use plain authentication so it knows which field is the username and which is the password to encode it in the right place. This means that having the encryption field configurable doesn't make sense for VST.

In http is uses the whole raw value as a replacement for the authentication header, having an encryption field on the Raw object would be odd for users of http as it would not be used.

**Comment by ruidscampos** [comment]
@nikita-vanyasin, any update on this?

**Comment by nikita-vanyasin** [comment]
@ajanikow @jwierzbo WDYT, can we include that into go-driver?

**Review by jwierzbo — APPROVED** [review]

**Comment by jwierzbo** [comment]
@ruidscampos please add short changelog (https://github.com/arangodb/go-driver/blob/master/CHANGELOG.md) + update with master.

**Comment by ruidscampos** [comment]
> @ruidscampos please add short changelog (https://github.com/arangodb/go-driver/blob/master/CHANGELOG.md) + update with master.

Please confirm all is in order now.

**Review by nikita-vanyasin — APPROVED** [review]

**Pull request merged**
