### PR TITLE
GT-379 Retriable batch reads in AQL cursors - V1

### PR DESCRIPTION
**Pull request by jwierzbo**

### CODE REVIEW

**Review by nikita-vanyasin — APPROVED** [review]
LGTM except that line on DOCKER_FWD_PORTS. How it is related to the PR?

**Comment by jwierzbo** [comment]
> LGTM except that line on DOCKER_FWD_PORTS. How it is related to the PR?

I've added it next to the DEBUG_PORT to open ports that allow you manually reach the Cluster members during the debugging session

**Review by informalict — APPROVED** [review]
lgtm

**Review by nikita-vanyasin — CHANGES_REQUESTED** [review]
Please don't merge until https://github.com/arangodb/go-driver/pull/501 is done

**Pull request merged**
