### PR TITLE
collection.properties - support cacheEnabled

### PR DESCRIPTION
**Pull request by robert-zaremba**
Updates `SetCollectionPropertiesOptions` and `CollectionProperties`
to support the new `cacheEnabled` property:
https://docs.arangodb.com/devel/Manual/ReleaseNotes/NewFeatures34.html#optional-caching-for-documents-and-primary-index-values

### CODE REVIEW

**Comment by robert-zaremba** [comment]
The Travis failure is not related to this PR. The CI setup is buggy - it doesn't download all dependencies.

**Comment by OmarAyo** [comment]
Hi @robert-zaremba 

Many thanks for contributing. We are obliged by law to have a signed scanned copy of a Contributor License Agreement (CLA) to be able to accept pull requests to the official ArangoDB repository - even for such small changes.

We use an Apache 2 CLA for ArangoDB and its companion projects, which can be found here: https://www.arangodb.com/documents/cla.pdf
Just fill in the form, sign and send a scanned copy over to cla@arangodb.com

Thank you

**Comment by robert-zaremba** [comment]
Done, signed and sent.

**Comment by OmarAyo** [comment]
Thanks

**Comment by robert-zaremba** [comment]
Can we merge this? I've got acknowledgement for CLA.

**Comment by maierlars** [comment]
This is missing a minimal test of creating a collection with cache enabled and reading it's properties to verify that it was set.

Please add this test. Then LGTM

**Comment by robert-zaremba** [comment]
@OmarAyo - I have difficulties to use that option.
It seams that I have my DB wrongly configured or something is missing in the documentation.
According to the latest [Collection documnentation](https://www.arangodb.com/docs/stable/data-modeling-collections-collection-methods.html#properties) there is no option for `cacheEnabled`. But is's mentioned in the [release notes](https://www.arangodb.com/docs/stable/release-notes-new-features34.html#optional-caching-for-documents-and-primary-index-values). 
I was trying to set that option manually *using arangosh) it works well:
```
127.0.0.1:8529@collection_test> db.test_collection_set_properties.properties({cacheEnabled: true })
{ 
  "isSystem" : false, 
  "waitForSync" : true, 
  "keyOptions" : { 
    "allowUserKeys" : true, 
    "type" : "traditional", 
    "lastValue" : 0 
  }, 
  ```

And as you can see it also works well. 
I'm using rocksdb engine.

**Comment by jwierzbo** [comment]
It is already implemented: https://github.com/arangodb/go-driver/commit/ca5dd87ffe9326ec275f6a592bd6b9b85f35608c

**Pull request closed without merging**
